# Generated by Django 3.2.4 on 2021-09-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0013_auto_20210813_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=240, unique=True),
        ),
    ]
