# Generated by Django 3.2.4 on 2021-09-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0014_alter_product_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'url'), name='user_url_unique'),
        ),
    ]
